fail_fast: false

repos:

  - repo: local
    hooks:
    - id: pre-commit
      name: Pre-commit git hook file
      entry: .github/hooks/pre-commit
      language: python
      additional_dependencies:
        - flake8
        - black

    - id: pytest-check
      name: pytest-check
      stages: [commit]
      types: [python]
      entry: pytest test/test.py
      language: system
    