apiVersion: v1
kind: Deployment
metadata:
  name: hvac-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hvac-controller
  template:
    metadata:
      labels:
        app: hvac-controller
    spec:
      containers:
      - name: hvac-controller-container
        image: hvac:latest
        env:
        - name: HOST
          valueFrom:
            configMagKeyRef:
              name: host
              key: HOST
        - name: DATABASE
          valueFrom:
            configMagKeyRef:
              name: database
              key: DATABASE
        - name: T_MIN
          valueFrom:
            configMagKeyRef:
              name: tmin
              key: T_MIN
        - name: T_MAX
          valueFrom:
            configMagKeyRef:
              name: tmax
              key: T_MAX
        - name: TICKETS
          valueFrom:
            configMagKeyRef:
              name: tickets
              key: TICKETS
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: token
              key: TOKEN
        - name: DATABASE_HOST
          value: database-service # Remplacez par nom du service base de données
        - name: POSTGRES_DB
          valueFrom:
            configMagKeyRef:
              name: postgresdb
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMagKeyRef:
              name: postgresuser
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: POSTGRES_PASSWORD
