apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-api
  template:
    metadata:
      labels:
        app: metrics-api
    spec:
      containers:
      - name: metrics-api-container
        image: pjbeltran/metrics:latest
        env:
        - name: DATABASE_HOST
          value: database-service
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgresdb
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgresuser
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: POSTGRES_PASSWORD
        resources:
            limits:
              memory: "100Mi"
              cpu: "0.2"