apiVersion: v1
kind: Deployment
metadata:
  name: metrics-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-api
  template:
    metadata:
      labels:
        app: metrics-api
    spec:
      containers:
      - name: metrics-api-container
        image: metrics:latest
        env:
        - name: DATABASE_HOST
          value: database-service # Remplacez par nom du service base de données
        - name: DATABASE_NAME
          value: postgres
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: postgres
