name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv
      run: pip install pipenv

    - name: Install pytest
      run: pip install pytest

    - name: Install signalrcore
      run: pip install signalrcore

    - name: Install psycopg2
      run: pip install psycopg2

    - name: Install python-dotenv
      run: pip install python-dotenv

    - name: Install dependencies
      run: pipenv install --dev --deploy

    - name: Run unit tests
      working-directory: ./test
      run: pytest test.py
      continue-on-error: false

    - name: Static code analysis
      run: pipenv run flake8 --max-line-length=90
      continue-on-error: false

    - name: Code formatting
      run: pipenv run black . --check
      continue-on-error: false

  docker-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: docker --version

    - name: Generate Date Tag
      id: date-tag
      run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"

    - name: Build Docker image
      run: |
        TAG=${{ steps.date-tag.outputs.tag }}
        docker build -t pjbeltran/hvac:latest -t pjbeltran/hvac:${TAG} .
        docker tag pjbeltran/hvac:latest pjbeltran/hvac:${TAG}

    - name: Log into Docker Hub
      if: github.ref == 'refs/heads/main'
      run: echo dckr_pat_lXwAYVQW8Wrr4y4BOG6AW2pOMYU | docker login -u pjbeltran --password-stdin

    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        TAG=${{ steps.date-tag.outputs.tag }}
        docker push pjbeltran/hvac:latest
        docker push pjbeltran/hvac:${TAG}
