name: Docker Build

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: docker --version

    - name: Build Docker image
      run: |
        docker build -t pjbeltran/hvac:${GITHUB_RUN_ID} .
        docker tag pjbeltran/hvac:${GITHUB_RUN_ID} pjbeltran/hvac:latest
      env:
        GITHUB_RUN_ID: ${{ github.run_id }}

    - name: Log into Docker Hub
      run: echo dckr_pat_lXwAYVQW8Wrr4y4BOG6AW2pOMYU | docker login -u pjbeltran --password-stdin

    - name: Push Docker image
      run: docker push pjbeltran/hvac:latest

