name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: docker --version

    - name: Generate Date Tag
      id: date-tag
      run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"  

    - name: Build Docker image
      run: |
        TAG=${{ steps.date-tag.outputs.tag }}
        docker build -t pjbeltran/hvac:latest -t pjbeltran/hvac:${TAG} .
        docker tag pjbeltran/hvac:latest pjbeltran/hvac:${TAG}

    - name: Log into Docker Hub
      run: echo dckr_pat_lXwAYVQW8Wrr4y4BOG6AW2pOMYU | docker login -u pjbeltran --password-stdin

    - name: Push Docker image
      run: |
        TAG=${{ steps.date-tag.outputs.tag }}
        docker push pjbeltran/hvac:latest
        docker push pjbeltran/hvac:${TAG}

